# Generated by Django 3.0.5 on 2020-04-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, default=0)),
                ('cic', models.CharField(db_index=True, max_length=15, verbose_name='Cedula CIC')),
                ('fullname', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('province', models.CharField(max_length=100, verbose_name='Departamento')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
            ],
        ),
    ]
