# Generated by Django 3.0.5 on 2020-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='social_code',
            field=models.CharField(default='', max_length=4, verbose_name='Programa social'),
        ),
    ]
