# Generated by Django 3.0.5 on 2020-04-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_social_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='post',
            name='province',
        ),
    ]
