# Generated by Django 3.0.5 on 2020-04-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_folio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, verbose_name='Codigo')),
            ],
        ),
    ]
