# Generated by Django 3.0.5 on 2020-04-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_socialprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprogram',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del programa'),
        ),
    ]
