# Generated by Django 3.0.5 on 2020-04-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_socialprogram_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('cic', 'social_code')},
        ),
    ]
