# Generated by Django 3.0.5 on 2020-04-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200417_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nangareko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cic', models.CharField(db_index=True, max_length=15, verbose_name='Cedula CIC')),
                ('fullname', models.CharField(blank=True, max_length=200, verbose_name='Nombre completo')),
                ('ignored', models.CharField(max_length=200, verbose_name='Ignorado')),
                ('carrier', models.CharField(max_length=100, verbose_name='Nueva operadora')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observacion')),
                ('payment_confirmed', models.CharField(max_length=200, verbose_name='Pago confirmado')),
                ('payment_solicited_bycarrier', models.CharField(max_length=200, verbose_name='Pago solicitado operadora')),
                ('sent_sms', models.CharField(max_length=200, verbose_name='Sms Enviado')),
                ('received_sms', models.CharField(max_length=200, verbose_name='Sms Recibido')),
                ('requested', models.CharField(blank=True, max_length=100, verbose_name='Solicitado a')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefono')),
            ],
            options={
                'unique_together': {('cic', 'phone')},
            },
        ),
    ]
